version: "3"
services:
    coupdepousse-node:
        image: "node:17.7-alpine"
        container_name: "coupdepousse-node"
        links:
          - "coupdepousse-mariadb:mariadb.host"
        ports:
          - 3000:3000
        volumes:
            - "./:/coupdepousse:rw"
        working_dir: /coupdepousse
        restart: always
        entrypoint: "/bin/sh -c -- \"while true; do sleep 10; done\""
    coupdepousse-mariadb:
        image: "mariadb:10.6"
        container_name: "coupdepousse-mariadb"
        volumes:
            - "._mysql_data_dir/:/var/lib/mysql:rw"
        ports:
          - 3307:3306
        environment:
          - MARIADB_USER
          - MARIADB_PASSWORD
          - MARIADB_DATABASE
          - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
        restart: always
    