apiVersion: v1
kind: Service
metadata:
  name: coupdepousse-service-external
spec:
  selector:
    app: coupdepousse
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer